server:
  port: 3000
db:
  type: 'mysql'
  host: 'localhost'
  port: 33061
  database: 'taskmanagement'
  username: 'root'
  password: '12345678'
  syncronize: true
jwt:
  expireIn: 3600
  secret: 'topSecret51'

  
